/* Focused renderer regression for the Nuked OPL boundary.
 *
 * The expected samples were generated by a separate harness that calls the
 * pinned Nuked implementation directly with OPL3_WriteRegBuffered() and
 * consumes the left channel.  This keeps the test independent of the two
 * wrapper mistakes it protects against: immediate register writes and an
 * L/R average downmix.
 */
#include "opl_backend.h"

#include <stdint.h>
#include <stdio.h>

static int check_sequence(void)
{
    static const uint8_t writes[][2] = {
        {0x20, 0x20}, {0x23, 0x20}, {0x40, 0x00}, {0x43, 0x00},
        {0x60, 0xF0}, {0x63, 0xF0}, {0x80, 0x0C}, {0x83, 0x0C},
        {0xC0, 0x01}, {0xA0, 0xAE}, {0xB0, 0x30},
    };
    static const int16_t expected_left[64] = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 67, 121, 222, 275, 329, 430, 482,
        542, 634, 687, 753, 840, 908, 993, 1045, 1118, 1197, 1249, 1328,
        1400, 1453, 1538, 1604, 1653, 1742, 1803, 1899, 1955, 2006, 2100,
        2156, 2207, 2303, 2349, 2409, 2496, 2557, 2646, 2697,
    };
    size_t i;

    opl_backend_reset(48000);
    for (i = 0; i < sizeof(writes) / sizeof(writes[0]); i++)
        opl_backend_write(writes[i][0], writes[i][1]);

    for (i = 0; i < sizeof(expected_left) / sizeof(expected_left[0]); i++) {
        float sample = opl_backend_generate();
        int16_t got = (int16_t)(sample * 32768.0f);
        if (got != expected_left[i]) {
            fprintf(stderr, "opl_backend_test: sample %zu: got %d, expected %d\n",
                    i, (int)got, (int)expected_left[i]);
            return 1;
        }
    }
    return 0;
}

int main(void)
{
    if (check_sequence() != 0)
        return 1;
    puts("opl_backend_test: OK");
    return 0;
}
