/* sound_driver_internal.h -- private layout helpers for sound_driver.c
 * (the asm/SOUND.ASM state-machine port, Phase 12 part 1).
 *
 * asm/SOUND.ASM addresses four generated byte blobs as "SI-indexed word
 * tables" (SI = voice*2 in the original register ABI; here just a plain
 * voice index 0..3):
 *
 *   - g17f4 (game_data.h: uint8_t g17f4[8])          -- one word table
 *   - sound_region_17C4 (uint8_t sound_region_17C4[40]) -- FIVE word
 *     tables packed back to back, 8 bytes (4 voices x 2 bytes) each, in
 *     this order (docs/current/sound-state.md "Structural finding"):
 *       +0  state_cursor        (17C4)
 *       +8  state_cursor_next   (17CC)
 *       +16 state_cursor_mode   (17D4)
 *       +24 state_text          (17DC)
 *       +32 voice_pending_table (17E4)
 *
 * The generator typed both blobs as raw uint8_t[] because their exact
 * per-word meaning was LOW confidence (see sound-state.md); the ASM reads/
 * writes them as 16-bit little-endian words per voice, so this header
 * gives that access pattern back via dos_rd16/dos_wr16 (project convention,
 * dos_types.h) instead of reinterpret-casting through a wider pointer type.
 */
#ifndef PORTABLE_AUDIO_SOUND_DRIVER_INTERNAL_H
#define PORTABLE_AUDIO_SOUND_DRIVER_INTERNAL_H

#include "dos_types.h"

#define SOUND_VOICE_COUNT_MAX 4

/* Defensive iteration cap for sound_driver.c's three ASM `for(;;)`-style
 * dispatch loops (sound_voice_pump_loop's rewind-and-reprime cycle,
 * sound_command_stream_dispatch, sound_stream_command_step). None of
 * these loops has an ASM-derived cap of its own -- a real command stream
 * never chains more than a handful of zero-duration commands back to
 * back, and a real per-voice table always has SOME voice either armed
 * (v_a!=0) or genuinely 0xFF-terminated -- but degenerate/not-yet-loaded
 * data (nothing armed, snd_flag2 pinned nonzero by an unrelated C write --
 * see sound-state.md's DS:1776 caveat) can otherwise spin the caller's
 * thread for a very long time doing no useful work, which read as a
 * game-visible freeze even though it is technically bounded (see the
 * port report). 256 is generous for any real stream while keeping the
 * worst-case cost per tick negligible (256 * a few dozen bytes of work,
 * not 100000+). */
#define SOUND_LOOP_GUARD_MAX 256

/* Byte offsets of the five word-tables packed into sound_region_17C4[40]. */
#define SOUND_REGION_STATE_CURSOR_OFF        0
#define SOUND_REGION_STATE_CURSOR_NEXT_OFF   8
#define SOUND_REGION_STATE_CURSOR_MODE_OFF  16
#define SOUND_REGION_STATE_TEXT_OFF         24
#define SOUND_REGION_VOICE_PENDING_OFF      32

static inline dos_int sound_region_word_get(const uint8_t *table_base, int sub_offset, dos_int voice)
{
    return (dos_int)dos_rd16(&table_base[sub_offset + (int)voice * 2]);
}

static inline void sound_region_word_set(uint8_t *table_base, int sub_offset, dos_int voice, dos_int value)
{
    dos_wr16(&table_base[sub_offset + (int)voice * 2], (uint16_t)value);
}

/* ---------------------------------------------------------------------
 * "17C4 mechanism" (pause-overlay byte-stream renderer, sound-state.md
 * LOW-confidence fields 17C4/17CC/1832) reinterpreted via generator
 * evidence:
 *
 * portable/generated/game_data.c's sound_dispatch_1832[36] is an array of
 * REAL C POINTERS (void*) into the lookup_XXXX byte blobs -- the generator
 * already resolved what asm/SOUND.ASM's `mov bx,[bx+1832h]` treated as a
 * 16-bit DS-relative "pointer word" into an actual pointer, because these
 * entries are constant, compile-time-known DATA (unlike runtime BSS state,
 * which the generator correctly leaves as plain 16-bit words since no
 * portable object can carry a full pointer in 16 bits).
 *
 * That leaves state_cursor/state_cursor_next (both runtime, 16-bit words
 * in sound_region_17C4) needing to reference one of those 36 real
 * pointers without a 16-bit field able to hold one. This port stores, in
 * both fields, an ENCODED (table_index:6, byte_position:10) pair instead
 * of a raw pointer -- 6 bits covers all 36 table entries, 10 bits covers
 * every entry's actual length (the longest, lookup_01f9, is 587 bytes;
 * all 36 stay under 1024). state_cursor is written once (by
 * sound_table_word_select_store) with position 0; state_cursor_next is
 * seeded from state_cursor at each reset and then walked byte by byte,
 * exactly mirroring the ASM's "seed state_cursor_next from state_cursor,
 * then increment it once per tick" behaviour -- only the pointer's
 * representation changed, not the stepping/termination semantics (each
 * lookup_XXXX blob still ends in a 0xFF sentinel byte, confirmed in
 * game_data.c). See sound_driver.c's port report for the full writeup. */
#define SOUND_STREAM_POS_BITS 10
#define SOUND_STREAM_POS_MASK ((1u << SOUND_STREAM_POS_BITS) - 1u) /* 0x3FF */
#define SOUND_STREAM_INDEX_MASK 0x3Fu                              /* 6 bits, >= 36 */

static inline uint16_t sound_stream_cursor_encode(unsigned index, unsigned pos)
{
    return (uint16_t)(((index & SOUND_STREAM_INDEX_MASK) << SOUND_STREAM_POS_BITS) |
                       (pos & SOUND_STREAM_POS_MASK));
}

static inline unsigned sound_stream_cursor_index(uint16_t v)
{
    return (unsigned)(v >> SOUND_STREAM_POS_BITS) & SOUND_STREAM_INDEX_MASK;
}

static inline unsigned sound_stream_cursor_pos(uint16_t v)
{
    return (unsigned)(v & SOUND_STREAM_POS_MASK);
}

/* ---------------------------------------------------------------------
 * "snd_seg/snd_base" and "snd_seg2/snd_base2" memory model.
 *
 * Historically these were DOS far-pointer halves: ES:DI addressing where
 * ES = the segment word (snd_seg or snd_seg2) and DI = an offset computed
 * from the paired offset word (snd_base/snd_base2) plus a table entry.
 * This driver owns two real pointers instead (sound.h:
 * sound_resource_block / sound_voice_block, set via
 * sound_set_resource_blocks() -- see that header's comment for the full
 * story and portable/game/plrldpub.c for the call site) and treats every
 * ES:DI-style access as a plain 16-bit offset relative to one of them,
 * through the resource_byte()/voice_byte()/resource_word()/voice_word()
 * helpers in sound_driver.c -- snd_seg/snd_seg2/snd_base/snd_base2 are
 * left at their generated zero default and never read for addressing. */

#endif /* PORTABLE_AUDIO_SOUND_DRIVER_INTERNAL_H */
