/* gfx_data_stub.c -- placeholder DAC color-lookup source tables.
 *
 * src/VIDEO.C F_0232 (color_lookup_tables_init) copies 32 bytes each from
 * DGROUP+0x9C (g9c) and DGROUP+0xDE (gde) into g3904[]/gbe[].  Those two
 * historical DATA tables are ordinary initialized game data, generated by
 * tools/portable/datagen.py from recipes/data/game-initialized.json once
 * portable/generated exists.  On this branch portable/generated does not
 * define them yet, so this translation unit supplies zero-filled
 * placeholders purely so portable/gfx links and its own tests can run
 * standalone.
 *
 * REMOVE this file's two definitions (the comment can stay as a pointer)
 * once portable/generated/game_data.c defines g9c/gde for real -- linking
 * both would be a duplicate-symbol error, which is the intended signal
 * that this stub is no longer needed.
 */
#include "dos_types.h"

const uint8_t g9c[32] = { 0 };
const uint8_t gde[32] = { 0 };
