/* test_resource.c -- decodes every record of assets/AE000.DAT and
 * assets/AE001.DAT through resource_load_record() and compares the result
 * (length + SHA-256 of the decoded bytes in ui_gfx_shadow_a, plus the
 * gc0cb type byte) against the golden manifest
 * portable/tests/fixtures/resource_golden.json, generated independently by
 * tools/portable/gen_resource_golden.py (tools/resource_codecs.py's
 * validated RLE/pair-span decoders + tools/portable/decode_ref.py's
 * from-scratch sprite-decoder transcription).
 *
 * Skips (return 77) when assets/AE000.DAT or assets/AE001.DAT are absent.
 *
 * No JSON library: the manifest is generated by our own script with a
 * fixed json.dump(..., indent=2, sort_keys=True) layout (2-space top-level
 * key lines, 4-space field lines, "gc0cb"/"s"/"sha256" or "skipped" in
 * that sorted order), so a small line-oriented parser tailored to exactly
 * that layout is enough; it is not a general JSON parser.
 */
#include "resource.h"
#include "sha256.h"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

typedef struct {
    char key[32];
    int have_data;   /* 1 if gc0cb/s/sha256 were parsed */
    int gc0cb;
    long s;
    char sha256[65];
    int skipped;
} golden_record;

static golden_record g_records[512];
static size_t g_record_count = 0;

static int starts_with_indent(const char *line, int spaces)
{
    int i;
    for (i = 0; i < spaces; i++) {
        if (line[i] != ' ') {
            return 0;
        }
    }
    return 1;
}

static void commit_record(golden_record *cur)
{
    if (cur->key[0] == '\0') {
        return;
    }
    if (g_record_count < sizeof(g_records) / sizeof(g_records[0])) {
        g_records[g_record_count++] = *cur;
    }
}

static int load_golden_manifest(const char *path)
{
    FILE *f = fopen(path, "r");
    char line[512];
    golden_record cur;
    int in_record = 0;

    if (!f) {
        fprintf(stderr, "test_resource: cannot open golden manifest %s\n", path);
        return -1;
    }

    memset(&cur, 0, sizeof cur);

    while (fgets(line, sizeof line, f)) {
        if (starts_with_indent(line, 2) && line[2] == '"') {
            char key[32];
            if (sscanf(line + 2, "\"%31[^\"]\"", key) == 1) {
                if (in_record) {
                    commit_record(&cur);
                }
                memset(&cur, 0, sizeof cur);
                strncpy(cur.key, key, sizeof(cur.key) - 1);
                in_record = 1;
            }
        } else if (in_record && starts_with_indent(line, 4) && line[4] == '"') {
            int gc0cb_val;
            long s;
            char strval[128];

            if (sscanf(line + 4, "\"gc0cb\": %d", &gc0cb_val) == 1) {
                cur.gc0cb = gc0cb_val;
                cur.have_data = 1;
            } else if (sscanf(line + 4, "\"s\": %ld", &s) == 1) {
                cur.s = s;
                cur.have_data = 1;
            } else if (sscanf(line + 4, "\"sha256\": \"%64[^\"]\"", strval) == 1) {
                strncpy(cur.sha256, strval, sizeof(cur.sha256) - 1);
                cur.have_data = 1;
            } else if (sscanf(line + 4, "\"skipped\": \"%127[^\"]\"", strval) == 1) {
                cur.skipped = 1;
            }
        } else if (in_record && starts_with_indent(line, 2) && line[2] == '}') {
            commit_record(&cur);
            memset(&cur, 0, sizeof cur);
            in_record = 0;
        }
    }
    if (in_record) {
        commit_record(&cur);
    }

    fclose(f);
    return 0;
}

static const golden_record *find_record(const char *key)
{
    size_t i;
    for (i = 0; i < g_record_count; i++) {
        if (strcmp(g_records[i].key, key) == 0) {
            return &g_records[i];
        }
    }
    return NULL;
}

static int file_exists(const char *path)
{
    FILE *f = fopen(path, "rb");
    if (!f) {
        return 0;
    }
    fclose(f);
    return 1;
}

int main(void)
{
    const char *asset_dir = EMPIRES_ASSET_DIR;
    const char *fixture_dir = EMPIRES_FIXTURE_DIR;
    char path[1024];
    int failures = 0;
    int checked = 0;
    int skipped = 0;
    static const char *const prefixes[2] = { "AE000", "AE001" };
    int dir;

    snprintf(path, sizeof path, "%s/AE000.DAT", asset_dir);
    if (!file_exists(path)) {
        printf("test_resource: %s not found, skipping\n", path);
        return 77;
    }
    snprintf(path, sizeof path, "%s/AE001.DAT", asset_dir);
    if (!file_exists(path)) {
        printf("test_resource: %s not found, skipping\n", path);
        return 77;
    }

    snprintf(path, sizeof path, "%s/resource_golden.json", fixture_dir);
    if (load_golden_manifest(path) != 0) {
        return 1;
    }
    printf("test_resource: loaded %zu golden entries from %s\n", g_record_count, path);

    resource_set_asset_dir(asset_dir);
    resource_staging_init();

    for (dir = 0; dir < 2; dir++) {
        unsigned count;
        unsigned i;

        if (resource_archive_open(dir) != 0) {
            fprintf(stderr, "test_resource: resource_archive_open(%d) failed\n", dir);
            failures++;
            continue;
        }
        count = resource_record_count(dir);
        printf("test_resource: %s.DAT: %u records\n", prefixes[dir], count);

        for (i = 0; i < count; i++) {
            char key[32];
            const golden_record *golden;
            dos_uint packed;
            dos_int s;
            char hex[65];

            snprintf(key, sizeof key, "%s_%03u", prefixes[dir], i);
            golden = find_record(key);
            if (!golden) {
                fprintf(stderr, "test_resource: %s: no golden entry\n", key);
                failures++;
                continue;
            }
            if (golden->skipped) {
                skipped++;
                continue;
            }

            packed = (dos_uint)(((dos_uint)dir << 12) | (dos_uint)i);
            s = resource_load_record(packed);
            checked++;

            if ((long)dos_u16(s) != golden->s) {
                fprintf(stderr, "test_resource: %s: length mismatch: got %ld, expected %ld\n",
                        key, (long)dos_u16(s), golden->s);
                failures++;
                continue;
            }
            if ((int)(unsigned char)gc0cb != golden->gc0cb) {
                fprintf(stderr, "test_resource: %s: gc0cb mismatch: got %d, expected %d\n",
                        key, (int)(unsigned char)gc0cb, golden->gc0cb);
                failures++;
            }

            sha256_hex(ui_gfx_shadow_a, (size_t)dos_u16(s), hex);
            if (strcmp(hex, golden->sha256) != 0) {
                fprintf(stderr, "test_resource: %s: sha256 mismatch: got %s, expected %s\n",
                        key, hex, golden->sha256);
                failures++;
            }
        }
    }

    resource_staging_shutdown();

    printf("test_resource: checked %d record(s), %d skipped, %d failure(s)\n",
           checked, skipped, failures);

    return failures ? 1 : 0;
}
